[general]
import = [
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[window]
opacity = 0.9

[font]
size = 12
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }

